services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: gidraf-dev:latest
    container_name: gidraf-dev
    ports:
      - "30200:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:3000" ]
      interval: 30s
      timeout: 5s
      retries: 3
